// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "encore.app/db"
	entity "encore.app/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBillRepository is a mock of BillRepository interface.
type MockBillRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillRepositoryMockRecorder
	isgomock struct{}
}

// MockBillRepositoryMockRecorder is the mock recorder for MockBillRepository.
type MockBillRepositoryMockRecorder struct {
	mock *MockBillRepository
}

// NewMockBillRepository creates a new mock instance.
func NewMockBillRepository(ctrl *gomock.Controller) *MockBillRepository {
	mock := &MockBillRepository{ctrl: ctrl}
	mock.recorder = &MockBillRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillRepository) EXPECT() *MockBillRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBillRepository) Close(ctx context.Context, billUUID string, closedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, billUUID, closedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBillRepositoryMockRecorder) Close(ctx, billUUID, closedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBillRepository)(nil).Close), ctx, billUUID, closedAt)
}

// FetchAll mocks base method.
func (m *MockBillRepository) FetchAll(ctx context.Context, params db.BillQueryParams) ([]*entity.BillEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].([]*entity.BillEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockBillRepositoryMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockBillRepository)(nil).FetchAll), ctx, params)
}

// FetchByUUID mocks base method.
func (m *MockBillRepository) FetchByUUID(ctx context.Context, uuid string) (*entity.BillEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUUID", ctx, uuid)
	ret0, _ := ret[0].(*entity.BillEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUUID indicates an expected call of FetchByUUID.
func (mr *MockBillRepositoryMockRecorder) FetchByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUUID", reflect.TypeOf((*MockBillRepository)(nil).FetchByUUID), ctx, uuid)
}

// FetchClosed mocks base method.
func (m *MockBillRepository) FetchClosed(ctx context.Context, billUUID string, fallbackClosedAt time.Time) (int64, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchClosed", ctx, billUUID, fallbackClosedAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchClosed indicates an expected call of FetchClosed.
func (mr *MockBillRepositoryMockRecorder) FetchClosed(ctx, billUUID, fallbackClosedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchClosed", reflect.TypeOf((*MockBillRepository)(nil).FetchClosed), ctx, billUUID, fallbackClosedAt)
}

// Insert mocks base method.
func (m *MockBillRepository) Insert(ctx context.Context, bill *entity.BillEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, bill)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockBillRepositoryMockRecorder) Insert(ctx, bill any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockBillRepository)(nil).Insert), ctx, bill)
}

// MockLineItemRepository is a mock of LineItemRepository interface.
type MockLineItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLineItemRepositoryMockRecorder
	isgomock struct{}
}

// MockLineItemRepositoryMockRecorder is the mock recorder for MockLineItemRepository.
type MockLineItemRepositoryMockRecorder struct {
	mock *MockLineItemRepository
}

// NewMockLineItemRepository creates a new mock instance.
func NewMockLineItemRepository(ctrl *gomock.Controller) *MockLineItemRepository {
	mock := &MockLineItemRepository{ctrl: ctrl}
	mock.recorder = &MockLineItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineItemRepository) EXPECT() *MockLineItemRepositoryMockRecorder {
	return m.recorder
}

// FetchByBillAndKey mocks base method.
func (m *MockLineItemRepository) FetchByBillAndKey(ctx context.Context, billUUID, idempotencyKey string) (*entity.LineItemEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByBillAndKey", ctx, billUUID, idempotencyKey)
	ret0, _ := ret[0].(*entity.LineItemEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByBillAndKey indicates an expected call of FetchByBillAndKey.
func (mr *MockLineItemRepositoryMockRecorder) FetchByBillAndKey(ctx, billUUID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByBillAndKey", reflect.TypeOf((*MockLineItemRepository)(nil).FetchByBillAndKey), ctx, billUUID, idempotencyKey)
}

// FetchByBillUUID mocks base method.
func (m *MockLineItemRepository) FetchByBillUUID(ctx context.Context, billUUID string, cursorTime time.Time, cursorID int64, limit int) ([]*entity.LineItemEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByBillUUID", ctx, billUUID, cursorTime, cursorID, limit)
	ret0, _ := ret[0].([]*entity.LineItemEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByBillUUID indicates an expected call of FetchByBillUUID.
func (mr *MockLineItemRepositoryMockRecorder) FetchByBillUUID(ctx, billUUID, cursorTime, cursorID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByBillUUID", reflect.TypeOf((*MockLineItemRepository)(nil).FetchByBillUUID), ctx, billUUID, cursorTime, cursorID, limit)
}

// FetchByUUID mocks base method.
func (m *MockLineItemRepository) FetchByUUID(ctx context.Context, uuid string) (*entity.LineItemEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUUID", ctx, uuid)
	ret0, _ := ret[0].(*entity.LineItemEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUUID indicates an expected call of FetchByUUID.
func (mr *MockLineItemRepositoryMockRecorder) FetchByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUUID", reflect.TypeOf((*MockLineItemRepository)(nil).FetchByUUID), ctx, uuid)
}

// FetchReversalByOriginalUUID mocks base method.
func (m *MockLineItemRepository) FetchReversalByOriginalUUID(ctx context.Context, originalUUID string) (*entity.LineItemEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchReversalByOriginalUUID", ctx, originalUUID)
	ret0, _ := ret[0].(*entity.LineItemEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchReversalByOriginalUUID indicates an expected call of FetchReversalByOriginalUUID.
func (mr *MockLineItemRepositoryMockRecorder) FetchReversalByOriginalUUID(ctx, originalUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchReversalByOriginalUUID", reflect.TypeOf((*MockLineItemRepository)(nil).FetchReversalByOriginalUUID), ctx, originalUUID)
}

// InsertWithBillUpdate mocks base method.
func (m *MockLineItemRepository) InsertWithBillUpdate(ctx context.Context, lineItem *entity.LineItemEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithBillUpdate", ctx, lineItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithBillUpdate indicates an expected call of InsertWithBillUpdate.
func (mr *MockLineItemRepositoryMockRecorder) InsertWithBillUpdate(ctx, lineItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithBillUpdate", reflect.TypeOf((*MockLineItemRepository)(nil).InsertWithBillUpdate), ctx, lineItem)
}

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// FetchByEmail mocks base method.
func (m *MockCustomerRepository) FetchByEmail(ctx context.Context, email string) (*entity.CustomerEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.CustomerEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByEmail indicates an expected call of FetchByEmail.
func (mr *MockCustomerRepositoryMockRecorder) FetchByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByEmail", reflect.TypeOf((*MockCustomerRepository)(nil).FetchByEmail), ctx, email)
}

// FetchByUUID mocks base method.
func (m *MockCustomerRepository) FetchByUUID(ctx context.Context, uuid string) (*entity.CustomerEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUUID", ctx, uuid)
	ret0, _ := ret[0].(*entity.CustomerEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUUID indicates an expected call of FetchByUUID.
func (mr *MockCustomerRepositoryMockRecorder) FetchByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUUID", reflect.TypeOf((*MockCustomerRepository)(nil).FetchByUUID), ctx, uuid)
}

// Insert mocks base method.
func (m *MockCustomerRepository) Insert(ctx context.Context, customer *entity.CustomerEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockCustomerRepositoryMockRecorder) Insert(ctx, customer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCustomerRepository)(nil).Insert), ctx, customer)
}
