// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (sql.Result, error)
	GetUserByUUID(ctx context.Context, db DBTX, userUuid string) (*User, error)
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
