// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users
    (user_uuid, name, status, created_at, updated_at)
VALUES
    (?, ?, ?, NOW(), NOW())
`

type CreateUserParams struct {
	UserUuid string `db:"user_uuid" json:"user_uuid"`
	Name     string `db:"name" json:"name"`
	Status   string `db:"status" json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (sql.Result, error) {
	return db.ExecContext(ctx, createUser, arg.UserUuid, arg.Name, arg.Status)
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, user_uuid, name, status, created_at, updated_at FROM users WHERE user_uuid = ?
`

func (q *Queries) GetUserByUUID(ctx context.Context, db DBTX, userUuid string) (*User, error) {
	row := db.QueryRowContext(ctx, getUserByUUID, userUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserUuid,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_uuid, name, status, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]*User, error) {
	rows, err := db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserUuid,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
